version: '3.4'

services:
  remote_weather_api:
    environment:
        - ASPNETCORE_ENVIRONMENT=Development.Docker
        - ASPNETCORE_URLS=http://+:5100;https://+:5101
        - DOTNET_USE_POLLING_FILE_WATCHER=1
        - NUGET_PACKAGES=/root/.nuget/fallbackpackages2
        - NUGET_FALLBACK_PACKAGES=/root/.nuget/fallbackpackages;/root/.nuget/fallbackpackages2
        - ASPNETCORE_Kestrel__Certificates__Default__Password=password
        - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
    ports:
        - "5100:5100"
        - "5101:5101"
  redis_cache_api:
    environment:
        - ASPNETCORE_ENVIRONMENT=Development.Docker
        - ASPNETCORE_URLS=http://+:5000;https://+:5001
        - ASPNETCORE_HTTPS_PORT=5101
        - DOTNET_USE_POLLING_FILE_WATCHER=1
        - NUGET_PACKAGES=/root/.nuget/fallbackpackages2
        - NUGET_FALLBACK_PACKAGES=/root/.nuget/fallbackpackages;/root/.nuget/fallbackpackages2
        - ASPNETCORE_Kestrel__Certificates__Default__Password=password
        - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
    ports:
        - "5000:5000"
        - "5001:5001"
  redis:
    ports:
        - "6479:6379"
        